# Generated by Django 2.1 on 2019-04-04 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evelist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tfield', models.CharField(max_length=100)),
                ('fifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evelist.Event')),
            ],
        ),
    ]
