# Generated by Django 2.1 on 2019-04-04 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='upvotes',
            new_name='upvote',
        ),
    ]
