# Generated by Django 2.1 on 2019-04-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_auto_20190404_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='myid',
            field=models.CharField(default='Zz3edcvuji876ty', max_length=100),
        ),
    ]
